// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface BytesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BytesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes imageBytes = 1;</code>
   */
  com.google.protobuf.ByteString getImageBytes();
}
