// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface BytesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BytesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes vectorBytes = 1;</code>
   */
  com.google.protobuf.ByteString getVectorBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
