// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface ImageBytesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImageBytes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes image = 1;</code>
   */
  com.google.protobuf.ByteString getImage();
}
