// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface LocateEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocateEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x1 = 1;</code>
   */
  int getX1();

  /**
   * <code>sint32 y1 = 2;</code>
   */
  int getY1();

  /**
   * <code>sint32 x2 = 3;</code>
   */
  int getX2();

  /**
   * <code>sint32 y2 = 4;</code>
   */
  int getY2();

  /**
   * <code>sint32 x3 = 5;</code>
   */
  int getX3();

  /**
   * <code>sint32 y3 = 6;</code>
   */
  int getY3();

  /**
   * <code>sint32 x4 = 7;</code>
   */
  int getX4();

  /**
   * <code>sint32 y4 = 8;</code>
   */
  int getY4();

  /**
   * <code>string type = 9;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 9;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string label = 10;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 10;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>bytes vector = 11;</code>
   */
  com.google.protobuf.ByteString getVector();

  /**
   * <code>float similarity = 12;</code>
   */
  float getSimilarity();
}
