// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

/**
 * <pre>
 *新增批量返回接口
 * </pre>
 *
 * Protobuf type {@code MBytesResponse}
 */
public  final class MBytesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MBytesResponse)
    MBytesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MBytesResponse.newBuilder() to construct.
  private MBytesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MBytesResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MBytesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              bytesResponseMap_ = com.google.protobuf.MapField.newMapField(
                  BytesResponseMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.BytesResponse>
            bytesResponseMap__ = input.readMessage(
                BytesResponseMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            bytesResponseMap_.getMutableMap().put(
                bytesResponseMap__.getKey(), bytesResponseMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetBytesResponseMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ac.iie.grpc.MBytesResponse.class, cn.ac.iie.grpc.MBytesResponse.Builder.class);
  }

  public static final int BYTESRESPONSEMAP_FIELD_NUMBER = 1;
  private static final class BytesResponseMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, cn.ac.iie.grpc.BytesResponse> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, cn.ac.iie.grpc.BytesResponse>newDefaultInstance(
                cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_BytesResponseMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                cn.ac.iie.grpc.BytesResponse.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, cn.ac.iie.grpc.BytesResponse> bytesResponseMap_;
  private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.BytesResponse>
  internalGetBytesResponseMap() {
    if (bytesResponseMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          BytesResponseMapDefaultEntryHolder.defaultEntry);
    }
    return bytesResponseMap_;
  }

  public int getBytesResponseMapCount() {
    return internalGetBytesResponseMap().getMap().size();
  }
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  public boolean containsBytesResponseMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetBytesResponseMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getBytesResponseMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> getBytesResponseMap() {
    return getBytesResponseMapMap();
  }
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  public java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> getBytesResponseMapMap() {
    return internalGetBytesResponseMap().getMap();
  }
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  public cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.BytesResponse defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> map =
        internalGetBytesResponseMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  public cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> map =
        internalGetBytesResponseMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetBytesResponseMap(),
        BytesResponseMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, cn.ac.iie.grpc.BytesResponse> entry
         : internalGetBytesResponseMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.BytesResponse>
      bytesResponseMap__ = BytesResponseMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bytesResponseMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ac.iie.grpc.MBytesResponse)) {
      return super.equals(obj);
    }
    cn.ac.iie.grpc.MBytesResponse other = (cn.ac.iie.grpc.MBytesResponse) obj;

    if (!internalGetBytesResponseMap().equals(
        other.internalGetBytesResponseMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetBytesResponseMap().getMap().isEmpty()) {
      hash = (37 * hash) + BYTESRESPONSEMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetBytesResponseMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MBytesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ac.iie.grpc.MBytesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *新增批量返回接口
   * </pre>
   *
   * Protobuf type {@code MBytesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MBytesResponse)
      cn.ac.iie.grpc.MBytesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetBytesResponseMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableBytesResponseMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ac.iie.grpc.MBytesResponse.class, cn.ac.iie.grpc.MBytesResponse.Builder.class);
    }

    // Construct using cn.ac.iie.grpc.MBytesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableBytesResponseMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MBytesResponse_descriptor;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MBytesResponse getDefaultInstanceForType() {
      return cn.ac.iie.grpc.MBytesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MBytesResponse build() {
      cn.ac.iie.grpc.MBytesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MBytesResponse buildPartial() {
      cn.ac.iie.grpc.MBytesResponse result = new cn.ac.iie.grpc.MBytesResponse(this);
      int from_bitField0_ = bitField0_;
      result.bytesResponseMap_ = internalGetBytesResponseMap();
      result.bytesResponseMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ac.iie.grpc.MBytesResponse) {
        return mergeFrom((cn.ac.iie.grpc.MBytesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ac.iie.grpc.MBytesResponse other) {
      if (other == cn.ac.iie.grpc.MBytesResponse.getDefaultInstance()) return this;
      internalGetMutableBytesResponseMap().mergeFrom(
          other.internalGetBytesResponseMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ac.iie.grpc.MBytesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ac.iie.grpc.MBytesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, cn.ac.iie.grpc.BytesResponse> bytesResponseMap_;
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.BytesResponse>
    internalGetBytesResponseMap() {
      if (bytesResponseMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BytesResponseMapDefaultEntryHolder.defaultEntry);
      }
      return bytesResponseMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.BytesResponse>
    internalGetMutableBytesResponseMap() {
      onChanged();;
      if (bytesResponseMap_ == null) {
        bytesResponseMap_ = com.google.protobuf.MapField.newMapField(
            BytesResponseMapDefaultEntryHolder.defaultEntry);
      }
      if (!bytesResponseMap_.isMutable()) {
        bytesResponseMap_ = bytesResponseMap_.copy();
      }
      return bytesResponseMap_;
    }

    public int getBytesResponseMapCount() {
      return internalGetBytesResponseMap().getMap().size();
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public boolean containsBytesResponseMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetBytesResponseMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBytesResponseMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> getBytesResponseMap() {
      return getBytesResponseMapMap();
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> getBytesResponseMapMap() {
      return internalGetBytesResponseMap().getMap();
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrDefault(
        java.lang.String key,
        cn.ac.iie.grpc.BytesResponse defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> map =
          internalGetBytesResponseMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> map =
          internalGetBytesResponseMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearBytesResponseMap() {
      internalGetMutableBytesResponseMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public Builder removeBytesResponseMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableBytesResponseMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse>
    getMutableBytesResponseMap() {
      return internalGetMutableBytesResponseMap().getMutableMap();
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */
    public Builder putBytesResponseMap(
        java.lang.String key,
        cn.ac.iie.grpc.BytesResponse value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableBytesResponseMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *key-id,value-bytesResponse
     * </pre>
     *
     * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
     */

    public Builder putAllBytesResponseMap(
        java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse> values) {
      internalGetMutableBytesResponseMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MBytesResponse)
  }

  // @@protoc_insertion_point(class_scope:MBytesResponse)
  private static final cn.ac.iie.grpc.MBytesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ac.iie.grpc.MBytesResponse();
  }

  public static cn.ac.iie.grpc.MBytesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MBytesResponse>
      PARSER = new com.google.protobuf.AbstractParser<MBytesResponse>() {
    @java.lang.Override
    public MBytesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MBytesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MBytesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MBytesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ac.iie.grpc.MBytesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

