// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface MBytesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MBytesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */
  int getBytesResponseMapCount();
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */
  boolean containsBytesResponseMap(
      java.lang.String key);
  /**
   * Use {@link #getBytesResponseMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse>
  getBytesResponseMap();
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */
  java.util.Map<java.lang.String, cn.ac.iie.grpc.BytesResponse>
  getBytesResponseMapMap();
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.BytesResponse defaultValue);
  /**
   * <pre>
   *key-id,value-bytesResponse
   * </pre>
   *
   * <code>map&lt;string, .BytesResponse&gt; BytesResponseMap = 1;</code>
   */

  cn.ac.iie.grpc.BytesResponse getBytesResponseMapOrThrow(
      java.lang.String key);
}
