// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface MediaTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MediaTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image_url = 1;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string failed = 3;</code>
   */
  java.lang.String getFailed();
  /**
   * <code>string failed = 3;</code>
   */
  com.google.protobuf.ByteString
      getFailedBytes();

  /**
   * <pre>
   *key:特征类型；value：特征向量。
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; image_vectors = 4;</code>
   */
  int getImageVectorsCount();
  /**
   * <pre>
   *key:特征类型；value：特征向量。
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; image_vectors = 4;</code>
   */
  boolean containsImageVectors(
      java.lang.String key);
  /**
   * Use {@link #getImageVectorsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getImageVectors();
  /**
   * <pre>
   *key:特征类型；value：特征向量。
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; image_vectors = 4;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getImageVectorsMap();
  /**
   * <pre>
   *key:特征类型；value：特征向量。
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; image_vectors = 4;</code>
   */

  com.google.protobuf.ByteString getImageVectorsOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <pre>
   *key:特征类型；value：特征向量。
   * </pre>
   *
   * <code>map&lt;string, bytes&gt; image_vectors = 4;</code>
   */

  com.google.protobuf.ByteString getImageVectorsOrThrow(
      java.lang.String key);
}
