// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface MImageUrlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MImageUrl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string urls = 1;</code>
   */
  java.util.List<java.lang.String>
      getUrlsList();
  /**
   * <code>repeated string urls = 1;</code>
   */
  int getUrlsCount();
  /**
   * <code>repeated string urls = 1;</code>
   */
  java.lang.String getUrls(int index);
  /**
   * <code>repeated string urls = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlsBytes(int index);
}
