// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

/**
 * <pre>
 *新增批量返回
 * </pre>
 *
 * Protobuf type {@code MLocateEntries}
 */
public  final class MLocateEntries extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MLocateEntries)
    MLocateEntriesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MLocateEntries.newBuilder() to construct.
  private MLocateEntries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MLocateEntries() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MLocateEntries(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              locatesMap_ = com.google.protobuf.MapField.newMapField(
                  LocatesMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.LocateEntries>
            locatesMap__ = input.readMessage(
                LocatesMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            locatesMap_.getMutableMap().put(
                locatesMap__.getKey(), locatesMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetLocatesMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ac.iie.grpc.MLocateEntries.class, cn.ac.iie.grpc.MLocateEntries.Builder.class);
  }

  public static final int LOCATESMAP_FIELD_NUMBER = 1;
  private static final class LocatesMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, cn.ac.iie.grpc.LocateEntries> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, cn.ac.iie.grpc.LocateEntries>newDefaultInstance(
                cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_LocatesMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                cn.ac.iie.grpc.LocateEntries.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, cn.ac.iie.grpc.LocateEntries> locatesMap_;
  private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.LocateEntries>
  internalGetLocatesMap() {
    if (locatesMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LocatesMapDefaultEntryHolder.defaultEntry);
    }
    return locatesMap_;
  }

  public int getLocatesMapCount() {
    return internalGetLocatesMap().getMap().size();
  }
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  public boolean containsLocatesMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetLocatesMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLocatesMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> getLocatesMap() {
    return getLocatesMapMap();
  }
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  public java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> getLocatesMapMap() {
    return internalGetLocatesMap().getMap();
  }
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  public cn.ac.iie.grpc.LocateEntries getLocatesMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.LocateEntries defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> map =
        internalGetLocatesMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  public cn.ac.iie.grpc.LocateEntries getLocatesMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> map =
        internalGetLocatesMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetLocatesMap(),
        LocatesMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, cn.ac.iie.grpc.LocateEntries> entry
         : internalGetLocatesMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.LocateEntries>
      locatesMap__ = LocatesMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, locatesMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ac.iie.grpc.MLocateEntries)) {
      return super.equals(obj);
    }
    cn.ac.iie.grpc.MLocateEntries other = (cn.ac.iie.grpc.MLocateEntries) obj;

    if (!internalGetLocatesMap().equals(
        other.internalGetLocatesMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetLocatesMap().getMap().isEmpty()) {
      hash = (37 * hash) + LOCATESMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLocatesMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MLocateEntries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ac.iie.grpc.MLocateEntries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *新增批量返回
   * </pre>
   *
   * Protobuf type {@code MLocateEntries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MLocateEntries)
      cn.ac.iie.grpc.MLocateEntriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetLocatesMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableLocatesMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ac.iie.grpc.MLocateEntries.class, cn.ac.iie.grpc.MLocateEntries.Builder.class);
    }

    // Construct using cn.ac.iie.grpc.MLocateEntries.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableLocatesMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MLocateEntries_descriptor;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MLocateEntries getDefaultInstanceForType() {
      return cn.ac.iie.grpc.MLocateEntries.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MLocateEntries build() {
      cn.ac.iie.grpc.MLocateEntries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MLocateEntries buildPartial() {
      cn.ac.iie.grpc.MLocateEntries result = new cn.ac.iie.grpc.MLocateEntries(this);
      int from_bitField0_ = bitField0_;
      result.locatesMap_ = internalGetLocatesMap();
      result.locatesMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ac.iie.grpc.MLocateEntries) {
        return mergeFrom((cn.ac.iie.grpc.MLocateEntries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ac.iie.grpc.MLocateEntries other) {
      if (other == cn.ac.iie.grpc.MLocateEntries.getDefaultInstance()) return this;
      internalGetMutableLocatesMap().mergeFrom(
          other.internalGetLocatesMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ac.iie.grpc.MLocateEntries parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ac.iie.grpc.MLocateEntries) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, cn.ac.iie.grpc.LocateEntries> locatesMap_;
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.LocateEntries>
    internalGetLocatesMap() {
      if (locatesMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LocatesMapDefaultEntryHolder.defaultEntry);
      }
      return locatesMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.LocateEntries>
    internalGetMutableLocatesMap() {
      onChanged();;
      if (locatesMap_ == null) {
        locatesMap_ = com.google.protobuf.MapField.newMapField(
            LocatesMapDefaultEntryHolder.defaultEntry);
      }
      if (!locatesMap_.isMutable()) {
        locatesMap_ = locatesMap_.copy();
      }
      return locatesMap_;
    }

    public int getLocatesMapCount() {
      return internalGetLocatesMap().getMap().size();
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public boolean containsLocatesMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetLocatesMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLocatesMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> getLocatesMap() {
      return getLocatesMapMap();
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> getLocatesMapMap() {
      return internalGetLocatesMap().getMap();
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public cn.ac.iie.grpc.LocateEntries getLocatesMapOrDefault(
        java.lang.String key,
        cn.ac.iie.grpc.LocateEntries defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> map =
          internalGetLocatesMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public cn.ac.iie.grpc.LocateEntries getLocatesMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> map =
          internalGetLocatesMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearLocatesMap() {
      internalGetMutableLocatesMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public Builder removeLocatesMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableLocatesMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries>
    getMutableLocatesMap() {
      return internalGetMutableLocatesMap().getMutableMap();
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */
    public Builder putLocatesMap(
        java.lang.String key,
        cn.ac.iie.grpc.LocateEntries value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableLocatesMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *key-url,value-locateEntries
     * </pre>
     *
     * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
     */

    public Builder putAllLocatesMap(
        java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries> values) {
      internalGetMutableLocatesMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MLocateEntries)
  }

  // @@protoc_insertion_point(class_scope:MLocateEntries)
  private static final cn.ac.iie.grpc.MLocateEntries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ac.iie.grpc.MLocateEntries();
  }

  public static cn.ac.iie.grpc.MLocateEntries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MLocateEntries>
      PARSER = new com.google.protobuf.AbstractParser<MLocateEntries>() {
    @java.lang.Override
    public MLocateEntries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MLocateEntries(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MLocateEntries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MLocateEntries> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ac.iie.grpc.MLocateEntries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

