// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface MLocateEntriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MLocateEntries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */
  int getLocatesMapCount();
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */
  boolean containsLocatesMap(
      java.lang.String key);
  /**
   * Use {@link #getLocatesMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries>
  getLocatesMap();
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */
  java.util.Map<java.lang.String, cn.ac.iie.grpc.LocateEntries>
  getLocatesMapMap();
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  cn.ac.iie.grpc.LocateEntries getLocatesMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.LocateEntries defaultValue);
  /**
   * <pre>
   *key-url,value-locateEntries
   * </pre>
   *
   * <code>map&lt;string, .LocateEntries&gt; locatesMap = 1;</code>
   */

  cn.ac.iie.grpc.LocateEntries getLocatesMapOrThrow(
      java.lang.String key);
}
