// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

/**
 * <pre>
 *新增批量请求接口
 * </pre>
 *
 * Protobuf type {@code MUrlRequest}
 */
public  final class MUrlRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MUrlRequest)
    MUrlRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MUrlRequest.newBuilder() to construct.
  private MUrlRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MUrlRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MUrlRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              urlRequestMap_ = com.google.protobuf.MapField.newMapField(
                  UrlRequestMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.UrlRequest>
            urlRequestMap__ = input.readMessage(
                UrlRequestMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            urlRequestMap_.getMutableMap().put(
                urlRequestMap__.getKey(), urlRequestMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetUrlRequestMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ac.iie.grpc.MUrlRequest.class, cn.ac.iie.grpc.MUrlRequest.Builder.class);
  }

  public static final int URLREQUESTMAP_FIELD_NUMBER = 1;
  private static final class UrlRequestMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, cn.ac.iie.grpc.UrlRequest> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, cn.ac.iie.grpc.UrlRequest>newDefaultInstance(
                cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_UrlRequestMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                cn.ac.iie.grpc.UrlRequest.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, cn.ac.iie.grpc.UrlRequest> urlRequestMap_;
  private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.UrlRequest>
  internalGetUrlRequestMap() {
    if (urlRequestMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UrlRequestMapDefaultEntryHolder.defaultEntry);
    }
    return urlRequestMap_;
  }

  public int getUrlRequestMapCount() {
    return internalGetUrlRequestMap().getMap().size();
  }
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  public boolean containsUrlRequestMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetUrlRequestMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUrlRequestMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> getUrlRequestMap() {
    return getUrlRequestMapMap();
  }
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  public java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> getUrlRequestMapMap() {
    return internalGetUrlRequestMap().getMap();
  }
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  public cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.UrlRequest defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> map =
        internalGetUrlRequestMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  public cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> map =
        internalGetUrlRequestMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUrlRequestMap(),
        UrlRequestMapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, cn.ac.iie.grpc.UrlRequest> entry
         : internalGetUrlRequestMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, cn.ac.iie.grpc.UrlRequest>
      urlRequestMap__ = UrlRequestMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, urlRequestMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ac.iie.grpc.MUrlRequest)) {
      return super.equals(obj);
    }
    cn.ac.iie.grpc.MUrlRequest other = (cn.ac.iie.grpc.MUrlRequest) obj;

    if (!internalGetUrlRequestMap().equals(
        other.internalGetUrlRequestMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetUrlRequestMap().getMap().isEmpty()) {
      hash = (37 * hash) + URLREQUESTMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUrlRequestMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.MUrlRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ac.iie.grpc.MUrlRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *新增批量请求接口
   * </pre>
   *
   * Protobuf type {@code MUrlRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MUrlRequest)
      cn.ac.iie.grpc.MUrlRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetUrlRequestMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableUrlRequestMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ac.iie.grpc.MUrlRequest.class, cn.ac.iie.grpc.MUrlRequest.Builder.class);
    }

    // Construct using cn.ac.iie.grpc.MUrlRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableUrlRequestMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ac.iie.grpc.VectorServer.internal_static_MUrlRequest_descriptor;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MUrlRequest getDefaultInstanceForType() {
      return cn.ac.iie.grpc.MUrlRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MUrlRequest build() {
      cn.ac.iie.grpc.MUrlRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.MUrlRequest buildPartial() {
      cn.ac.iie.grpc.MUrlRequest result = new cn.ac.iie.grpc.MUrlRequest(this);
      int from_bitField0_ = bitField0_;
      result.urlRequestMap_ = internalGetUrlRequestMap();
      result.urlRequestMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ac.iie.grpc.MUrlRequest) {
        return mergeFrom((cn.ac.iie.grpc.MUrlRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ac.iie.grpc.MUrlRequest other) {
      if (other == cn.ac.iie.grpc.MUrlRequest.getDefaultInstance()) return this;
      internalGetMutableUrlRequestMap().mergeFrom(
          other.internalGetUrlRequestMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ac.iie.grpc.MUrlRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ac.iie.grpc.MUrlRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, cn.ac.iie.grpc.UrlRequest> urlRequestMap_;
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.UrlRequest>
    internalGetUrlRequestMap() {
      if (urlRequestMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UrlRequestMapDefaultEntryHolder.defaultEntry);
      }
      return urlRequestMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, cn.ac.iie.grpc.UrlRequest>
    internalGetMutableUrlRequestMap() {
      onChanged();;
      if (urlRequestMap_ == null) {
        urlRequestMap_ = com.google.protobuf.MapField.newMapField(
            UrlRequestMapDefaultEntryHolder.defaultEntry);
      }
      if (!urlRequestMap_.isMutable()) {
        urlRequestMap_ = urlRequestMap_.copy();
      }
      return urlRequestMap_;
    }

    public int getUrlRequestMapCount() {
      return internalGetUrlRequestMap().getMap().size();
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public boolean containsUrlRequestMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetUrlRequestMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUrlRequestMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> getUrlRequestMap() {
      return getUrlRequestMapMap();
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> getUrlRequestMapMap() {
      return internalGetUrlRequestMap().getMap();
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrDefault(
        java.lang.String key,
        cn.ac.iie.grpc.UrlRequest defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> map =
          internalGetUrlRequestMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> map =
          internalGetUrlRequestMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUrlRequestMap() {
      internalGetMutableUrlRequestMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public Builder removeUrlRequestMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableUrlRequestMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest>
    getMutableUrlRequestMap() {
      return internalGetMutableUrlRequestMap().getMutableMap();
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */
    public Builder putUrlRequestMap(
        java.lang.String key,
        cn.ac.iie.grpc.UrlRequest value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableUrlRequestMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *key-id,value-urlRequest
     * </pre>
     *
     * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
     */

    public Builder putAllUrlRequestMap(
        java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest> values) {
      internalGetMutableUrlRequestMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MUrlRequest)
  }

  // @@protoc_insertion_point(class_scope:MUrlRequest)
  private static final cn.ac.iie.grpc.MUrlRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ac.iie.grpc.MUrlRequest();
  }

  public static cn.ac.iie.grpc.MUrlRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MUrlRequest>
      PARSER = new com.google.protobuf.AbstractParser<MUrlRequest>() {
    @java.lang.Override
    public MUrlRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MUrlRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MUrlRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MUrlRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ac.iie.grpc.MUrlRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

