// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface MUrlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MUrlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */
  int getUrlRequestMapCount();
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */
  boolean containsUrlRequestMap(
      java.lang.String key);
  /**
   * Use {@link #getUrlRequestMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest>
  getUrlRequestMap();
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */
  java.util.Map<java.lang.String, cn.ac.iie.grpc.UrlRequest>
  getUrlRequestMapMap();
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrDefault(
      java.lang.String key,
      cn.ac.iie.grpc.UrlRequest defaultValue);
  /**
   * <pre>
   *key-id,value-urlRequest
   * </pre>
   *
   * <code>map&lt;string, .UrlRequest&gt; UrlRequestMap = 1;</code>
   */

  cn.ac.iie.grpc.UrlRequest getUrlRequestMapOrThrow(
      java.lang.String key);
}
