// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface QueryByBytesEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryByBytesEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string space = 1;</code>
   */
  java.lang.String getSpace();
  /**
   * <code>string space = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpaceBytes();

  /**
   * <code>int64 startTime = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 endTime = 3;</code>
   */
  long getEndTime();

  /**
   * <code>.BytesRequest image = 8;</code>
   */
  boolean hasImage();
  /**
   * <code>.BytesRequest image = 8;</code>
   */
  cn.ac.iie.grpc.BytesRequest getImage();
  /**
   * <code>.BytesRequest image = 8;</code>
   */
  cn.ac.iie.grpc.BytesRequestOrBuilder getImageOrBuilder();
}
