// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

/**
 * <pre>
 *4.对外接口
 * </pre>
 *
 * Protobuf type {@code QueryByBytesEntry}
 */
public  final class QueryByBytesEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QueryByBytesEntry)
    QueryByBytesEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryByBytesEntry.newBuilder() to construct.
  private QueryByBytesEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryByBytesEntry() {
    space_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryByBytesEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            space_ = s;
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            endTime_ = input.readInt64();
            break;
          }
          case 66: {
            cn.ac.iie.grpc.BytesRequest.Builder subBuilder = null;
            if (image_ != null) {
              subBuilder = image_.toBuilder();
            }
            image_ = input.readMessage(cn.ac.iie.grpc.BytesRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(image_);
              image_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ac.iie.grpc.VectorServer.internal_static_QueryByBytesEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ac.iie.grpc.VectorServer.internal_static_QueryByBytesEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ac.iie.grpc.QueryByBytesEntry.class, cn.ac.iie.grpc.QueryByBytesEntry.Builder.class);
  }

  public static final int SPACE_FIELD_NUMBER = 1;
  private volatile java.lang.Object space_;
  /**
   * <code>string space = 1;</code>
   */
  public java.lang.String getSpace() {
    java.lang.Object ref = space_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      space_ = s;
      return s;
    }
  }
  /**
   * <code>string space = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSpaceBytes() {
    java.lang.Object ref = space_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      space_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <code>int64 startTime = 2;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  private long endTime_;
  /**
   * <code>int64 endTime = 3;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int IMAGE_FIELD_NUMBER = 8;
  private cn.ac.iie.grpc.BytesRequest image_;
  /**
   * <code>.BytesRequest image = 8;</code>
   */
  public boolean hasImage() {
    return image_ != null;
  }
  /**
   * <code>.BytesRequest image = 8;</code>
   */
  public cn.ac.iie.grpc.BytesRequest getImage() {
    return image_ == null ? cn.ac.iie.grpc.BytesRequest.getDefaultInstance() : image_;
  }
  /**
   * <code>.BytesRequest image = 8;</code>
   */
  public cn.ac.iie.grpc.BytesRequestOrBuilder getImageOrBuilder() {
    return getImage();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSpaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, space_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(3, endTime_);
    }
    if (image_ != null) {
      output.writeMessage(8, getImage());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSpaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, space_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, endTime_);
    }
    if (image_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getImage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ac.iie.grpc.QueryByBytesEntry)) {
      return super.equals(obj);
    }
    cn.ac.iie.grpc.QueryByBytesEntry other = (cn.ac.iie.grpc.QueryByBytesEntry) obj;

    if (!getSpace()
        .equals(other.getSpace())) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (hasImage() != other.hasImage()) return false;
    if (hasImage()) {
      if (!getImage()
          .equals(other.getImage())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SPACE_FIELD_NUMBER;
    hash = (53 * hash) + getSpace().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.QueryByBytesEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ac.iie.grpc.QueryByBytesEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *4.对外接口
   * </pre>
   *
   * Protobuf type {@code QueryByBytesEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QueryByBytesEntry)
      cn.ac.iie.grpc.QueryByBytesEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ac.iie.grpc.VectorServer.internal_static_QueryByBytesEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ac.iie.grpc.VectorServer.internal_static_QueryByBytesEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ac.iie.grpc.QueryByBytesEntry.class, cn.ac.iie.grpc.QueryByBytesEntry.Builder.class);
    }

    // Construct using cn.ac.iie.grpc.QueryByBytesEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      space_ = "";

      startTime_ = 0L;

      endTime_ = 0L;

      if (imageBuilder_ == null) {
        image_ = null;
      } else {
        image_ = null;
        imageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ac.iie.grpc.VectorServer.internal_static_QueryByBytesEntry_descriptor;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.QueryByBytesEntry getDefaultInstanceForType() {
      return cn.ac.iie.grpc.QueryByBytesEntry.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ac.iie.grpc.QueryByBytesEntry build() {
      cn.ac.iie.grpc.QueryByBytesEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.QueryByBytesEntry buildPartial() {
      cn.ac.iie.grpc.QueryByBytesEntry result = new cn.ac.iie.grpc.QueryByBytesEntry(this);
      result.space_ = space_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      if (imageBuilder_ == null) {
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ac.iie.grpc.QueryByBytesEntry) {
        return mergeFrom((cn.ac.iie.grpc.QueryByBytesEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ac.iie.grpc.QueryByBytesEntry other) {
      if (other == cn.ac.iie.grpc.QueryByBytesEntry.getDefaultInstance()) return this;
      if (!other.getSpace().isEmpty()) {
        space_ = other.space_;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ac.iie.grpc.QueryByBytesEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ac.iie.grpc.QueryByBytesEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object space_ = "";
    /**
     * <code>string space = 1;</code>
     */
    public java.lang.String getSpace() {
      java.lang.Object ref = space_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        space_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string space = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSpaceBytes() {
      java.lang.Object ref = space_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        space_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string space = 1;</code>
     */
    public Builder setSpace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      space_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string space = 1;</code>
     */
    public Builder clearSpace() {
      
      space_ = getDefaultInstance().getSpace();
      onChanged();
      return this;
    }
    /**
     * <code>string space = 1;</code>
     */
    public Builder setSpaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      space_ = value;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 startTime = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 2;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 2;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 3;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 3;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 3;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private cn.ac.iie.grpc.BytesRequest image_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.ac.iie.grpc.BytesRequest, cn.ac.iie.grpc.BytesRequest.Builder, cn.ac.iie.grpc.BytesRequestOrBuilder> imageBuilder_;
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public boolean hasImage() {
      return imageBuilder_ != null || image_ != null;
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public cn.ac.iie.grpc.BytesRequest getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? cn.ac.iie.grpc.BytesRequest.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public Builder setImage(cn.ac.iie.grpc.BytesRequest value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
        onChanged();
      } else {
        imageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public Builder setImage(
        cn.ac.iie.grpc.BytesRequest.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
        onChanged();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public Builder mergeImage(cn.ac.iie.grpc.BytesRequest value) {
      if (imageBuilder_ == null) {
        if (image_ != null) {
          image_ =
            cn.ac.iie.grpc.BytesRequest.newBuilder(image_).mergeFrom(value).buildPartial();
        } else {
          image_ = value;
        }
        onChanged();
      } else {
        imageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = null;
        onChanged();
      } else {
        image_ = null;
        imageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public cn.ac.iie.grpc.BytesRequest.Builder getImageBuilder() {
      
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    public cn.ac.iie.grpc.BytesRequestOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            cn.ac.iie.grpc.BytesRequest.getDefaultInstance() : image_;
      }
    }
    /**
     * <code>.BytesRequest image = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.ac.iie.grpc.BytesRequest, cn.ac.iie.grpc.BytesRequest.Builder, cn.ac.iie.grpc.BytesRequestOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.ac.iie.grpc.BytesRequest, cn.ac.iie.grpc.BytesRequest.Builder, cn.ac.iie.grpc.BytesRequestOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QueryByBytesEntry)
  }

  // @@protoc_insertion_point(class_scope:QueryByBytesEntry)
  private static final cn.ac.iie.grpc.QueryByBytesEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ac.iie.grpc.QueryByBytesEntry();
  }

  public static cn.ac.iie.grpc.QueryByBytesEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryByBytesEntry>
      PARSER = new com.google.protobuf.AbstractParser<QueryByBytesEntry>() {
    @java.lang.Override
    public QueryByBytesEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryByBytesEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryByBytesEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryByBytesEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ac.iie.grpc.QueryByBytesEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

