// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface ResultEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string space = 1;</code>
   */
  java.lang.String getSpace();
  /**
   * <code>string space = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpaceBytes();

  /**
   * <code>string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>int64 startTime = 3;</code>
   */
  long getStartTime();

  /**
   * <code>int64 endTime = 4;</code>
   */
  long getEndTime();

  /**
   * <code>bytes vector = 5;</code>
   */
  com.google.protobuf.ByteString getVector();
}
