// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

/**
 * Protobuf type {@code ResultEntryHash}
 */
public  final class ResultEntryHash extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ResultEntryHash)
    ResultEntryHashOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultEntryHash.newBuilder() to construct.
  private ResultEntryHash(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultEntryHash() {
    resultEntries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResultEntryHash(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              resultEntries_ = new java.util.ArrayList<cn.ac.iie.grpc.ResultEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            resultEntries_.add(
                input.readMessage(cn.ac.iie.grpc.ResultEntry.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        resultEntries_ = java.util.Collections.unmodifiableList(resultEntries_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ac.iie.grpc.VectorServer.internal_static_ResultEntryHash_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ac.iie.grpc.VectorServer.internal_static_ResultEntryHash_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ac.iie.grpc.ResultEntryHash.class, cn.ac.iie.grpc.ResultEntryHash.Builder.class);
  }

  public static final int RESULTENTRIES_FIELD_NUMBER = 1;
  private java.util.List<cn.ac.iie.grpc.ResultEntry> resultEntries_;
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  public java.util.List<cn.ac.iie.grpc.ResultEntry> getResultEntriesList() {
    return resultEntries_;
  }
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  public java.util.List<? extends cn.ac.iie.grpc.ResultEntryOrBuilder> 
      getResultEntriesOrBuilderList() {
    return resultEntries_;
  }
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  public int getResultEntriesCount() {
    return resultEntries_.size();
  }
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  public cn.ac.iie.grpc.ResultEntry getResultEntries(int index) {
    return resultEntries_.get(index);
  }
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  public cn.ac.iie.grpc.ResultEntryOrBuilder getResultEntriesOrBuilder(
      int index) {
    return resultEntries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resultEntries_.size(); i++) {
      output.writeMessage(1, resultEntries_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resultEntries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resultEntries_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ac.iie.grpc.ResultEntryHash)) {
      return super.equals(obj);
    }
    cn.ac.iie.grpc.ResultEntryHash other = (cn.ac.iie.grpc.ResultEntryHash) obj;

    if (!getResultEntriesList()
        .equals(other.getResultEntriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultEntriesCount() > 0) {
      hash = (37 * hash) + RESULTENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getResultEntriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ac.iie.grpc.ResultEntryHash parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ac.iie.grpc.ResultEntryHash prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ResultEntryHash}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ResultEntryHash)
      cn.ac.iie.grpc.ResultEntryHashOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ac.iie.grpc.VectorServer.internal_static_ResultEntryHash_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ac.iie.grpc.VectorServer.internal_static_ResultEntryHash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ac.iie.grpc.ResultEntryHash.class, cn.ac.iie.grpc.ResultEntryHash.Builder.class);
    }

    // Construct using cn.ac.iie.grpc.ResultEntryHash.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultEntriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resultEntriesBuilder_ == null) {
        resultEntries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultEntriesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ac.iie.grpc.VectorServer.internal_static_ResultEntryHash_descriptor;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.ResultEntryHash getDefaultInstanceForType() {
      return cn.ac.iie.grpc.ResultEntryHash.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ac.iie.grpc.ResultEntryHash build() {
      cn.ac.iie.grpc.ResultEntryHash result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ac.iie.grpc.ResultEntryHash buildPartial() {
      cn.ac.iie.grpc.ResultEntryHash result = new cn.ac.iie.grpc.ResultEntryHash(this);
      int from_bitField0_ = bitField0_;
      if (resultEntriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resultEntries_ = java.util.Collections.unmodifiableList(resultEntries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resultEntries_ = resultEntries_;
      } else {
        result.resultEntries_ = resultEntriesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ac.iie.grpc.ResultEntryHash) {
        return mergeFrom((cn.ac.iie.grpc.ResultEntryHash)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ac.iie.grpc.ResultEntryHash other) {
      if (other == cn.ac.iie.grpc.ResultEntryHash.getDefaultInstance()) return this;
      if (resultEntriesBuilder_ == null) {
        if (!other.resultEntries_.isEmpty()) {
          if (resultEntries_.isEmpty()) {
            resultEntries_ = other.resultEntries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultEntriesIsMutable();
            resultEntries_.addAll(other.resultEntries_);
          }
          onChanged();
        }
      } else {
        if (!other.resultEntries_.isEmpty()) {
          if (resultEntriesBuilder_.isEmpty()) {
            resultEntriesBuilder_.dispose();
            resultEntriesBuilder_ = null;
            resultEntries_ = other.resultEntries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultEntriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultEntriesFieldBuilder() : null;
          } else {
            resultEntriesBuilder_.addAllMessages(other.resultEntries_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ac.iie.grpc.ResultEntryHash parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ac.iie.grpc.ResultEntryHash) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cn.ac.iie.grpc.ResultEntry> resultEntries_ =
      java.util.Collections.emptyList();
    private void ensureResultEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resultEntries_ = new java.util.ArrayList<cn.ac.iie.grpc.ResultEntry>(resultEntries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ac.iie.grpc.ResultEntry, cn.ac.iie.grpc.ResultEntry.Builder, cn.ac.iie.grpc.ResultEntryOrBuilder> resultEntriesBuilder_;

    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public java.util.List<cn.ac.iie.grpc.ResultEntry> getResultEntriesList() {
      if (resultEntriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resultEntries_);
      } else {
        return resultEntriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public int getResultEntriesCount() {
      if (resultEntriesBuilder_ == null) {
        return resultEntries_.size();
      } else {
        return resultEntriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public cn.ac.iie.grpc.ResultEntry getResultEntries(int index) {
      if (resultEntriesBuilder_ == null) {
        return resultEntries_.get(index);
      } else {
        return resultEntriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder setResultEntries(
        int index, cn.ac.iie.grpc.ResultEntry value) {
      if (resultEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntriesIsMutable();
        resultEntries_.set(index, value);
        onChanged();
      } else {
        resultEntriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder setResultEntries(
        int index, cn.ac.iie.grpc.ResultEntry.Builder builderForValue) {
      if (resultEntriesBuilder_ == null) {
        ensureResultEntriesIsMutable();
        resultEntries_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultEntriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder addResultEntries(cn.ac.iie.grpc.ResultEntry value) {
      if (resultEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntriesIsMutable();
        resultEntries_.add(value);
        onChanged();
      } else {
        resultEntriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder addResultEntries(
        int index, cn.ac.iie.grpc.ResultEntry value) {
      if (resultEntriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultEntriesIsMutable();
        resultEntries_.add(index, value);
        onChanged();
      } else {
        resultEntriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder addResultEntries(
        cn.ac.iie.grpc.ResultEntry.Builder builderForValue) {
      if (resultEntriesBuilder_ == null) {
        ensureResultEntriesIsMutable();
        resultEntries_.add(builderForValue.build());
        onChanged();
      } else {
        resultEntriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder addResultEntries(
        int index, cn.ac.iie.grpc.ResultEntry.Builder builderForValue) {
      if (resultEntriesBuilder_ == null) {
        ensureResultEntriesIsMutable();
        resultEntries_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultEntriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder addAllResultEntries(
        java.lang.Iterable<? extends cn.ac.iie.grpc.ResultEntry> values) {
      if (resultEntriesBuilder_ == null) {
        ensureResultEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resultEntries_);
        onChanged();
      } else {
        resultEntriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder clearResultEntries() {
      if (resultEntriesBuilder_ == null) {
        resultEntries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultEntriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public Builder removeResultEntries(int index) {
      if (resultEntriesBuilder_ == null) {
        ensureResultEntriesIsMutable();
        resultEntries_.remove(index);
        onChanged();
      } else {
        resultEntriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public cn.ac.iie.grpc.ResultEntry.Builder getResultEntriesBuilder(
        int index) {
      return getResultEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public cn.ac.iie.grpc.ResultEntryOrBuilder getResultEntriesOrBuilder(
        int index) {
      if (resultEntriesBuilder_ == null) {
        return resultEntries_.get(index);  } else {
        return resultEntriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public java.util.List<? extends cn.ac.iie.grpc.ResultEntryOrBuilder> 
         getResultEntriesOrBuilderList() {
      if (resultEntriesBuilder_ != null) {
        return resultEntriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resultEntries_);
      }
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public cn.ac.iie.grpc.ResultEntry.Builder addResultEntriesBuilder() {
      return getResultEntriesFieldBuilder().addBuilder(
          cn.ac.iie.grpc.ResultEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public cn.ac.iie.grpc.ResultEntry.Builder addResultEntriesBuilder(
        int index) {
      return getResultEntriesFieldBuilder().addBuilder(
          index, cn.ac.iie.grpc.ResultEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .ResultEntry ResultEntries = 1;</code>
     */
    public java.util.List<cn.ac.iie.grpc.ResultEntry.Builder> 
         getResultEntriesBuilderList() {
      return getResultEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ac.iie.grpc.ResultEntry, cn.ac.iie.grpc.ResultEntry.Builder, cn.ac.iie.grpc.ResultEntryOrBuilder> 
        getResultEntriesFieldBuilder() {
      if (resultEntriesBuilder_ == null) {
        resultEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.ac.iie.grpc.ResultEntry, cn.ac.iie.grpc.ResultEntry.Builder, cn.ac.iie.grpc.ResultEntryOrBuilder>(
                resultEntries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resultEntries_ = null;
      }
      return resultEntriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ResultEntryHash)
  }

  // @@protoc_insertion_point(class_scope:ResultEntryHash)
  private static final cn.ac.iie.grpc.ResultEntryHash DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ac.iie.grpc.ResultEntryHash();
  }

  public static cn.ac.iie.grpc.ResultEntryHash getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultEntryHash>
      PARSER = new com.google.protobuf.AbstractParser<ResultEntryHash>() {
    @java.lang.Override
    public ResultEntryHash parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResultEntryHash(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResultEntryHash> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultEntryHash> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ac.iie.grpc.ResultEntryHash getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

