// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface UrlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UrlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x1 = 1;</code>
   */
  int getX1();

  /**
   * <code>sint32 y1 = 2;</code>
   */
  int getY1();

  /**
   * <code>sint32 x2 = 3;</code>
   */
  int getX2();

  /**
   * <code>sint32 y2 = 4;</code>
   */
  int getY2();

  /**
   * <code>sint32 x3 = 5;</code>
   */
  int getX3();

  /**
   * <code>sint32 y3 = 6;</code>
   */
  int getY3();

  /**
   * <code>sint32 x4 = 7;</code>
   */
  int getX4();

  /**
   * <code>sint32 y4 = 8;</code>
   */
  int getY4();

  /**
   * <code>string imageUrl = 9;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string imageUrl = 9;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
