// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public interface VectorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VectorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; batchQuery = 1;</code>
   */
  int getBatchQueryCount();
  /**
   * <code>map&lt;string, string&gt; batchQuery = 1;</code>
   */
  boolean containsBatchQuery(
      java.lang.String key);
  /**
   * Use {@link #getBatchQueryMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getBatchQuery();
  /**
   * <code>map&lt;string, string&gt; batchQuery = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getBatchQueryMap();
  /**
   * <code>map&lt;string, string&gt; batchQuery = 1;</code>
   */

  java.lang.String getBatchQueryOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; batchQuery = 1;</code>
   */

  java.lang.String getBatchQueryOrThrow(
      java.lang.String key);
}
