// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package cn.ac.iie.grpc;

public final class VectorServer {
  private VectorServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BytesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BytesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BytesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BytesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BytesResponse_VectorBytesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BytesResponse_VectorBytesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorRequest_BatchQueryEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorRequest_BatchQueryEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MediaTask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MediaTask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MediaTask_ImageVectorsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MediaTask_ImageVectorsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorResponse_BatchVectorEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorResponse_BatchVectorEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014vector.proto\"\"\n\014BytesRequest\022\022\n\nimageB" +
      "ytes\030\001 \001(\014\"\207\001\n\rBytesResponse\0224\n\013vectorBy" +
      "tes\030\001 \003(\0132\037.BytesResponse.VectorBytesEnt" +
      "ry\022\014\n\004code\030\002 \001(\t\0322\n\020VectorBytesEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"v\n\rVectorRe" +
      "quest\0222\n\nbatchQuery\030\001 \003(\0132\036.VectorReques" +
      "t.BatchQueryEntry\0321\n\017BatchQueryEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\246\001\n\tMediaTa" +
      "sk\022\021\n\timage_url\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\016\n\006f" +
      "ailed\030\003 \001(\t\0223\n\rimage_vectors\030\004 \003(\0132\034.Med" +
      "iaTask.ImageVectorsEntry\0323\n\021ImageVectors" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\207\001" +
      "\n\016VectorResponse\0225\n\013batchVector\030\001 \003(\0132 ." +
      "VectorResponse.BatchVectorEntry\032>\n\020Batch" +
      "VectorEntry\022\013\n\003key\030\001 \001(\t\022\031\n\005value\030\002 \001(\0132" +
      "\n.MediaTask:\0028\0012g\n\006Vector\022+\n\006search\022\016.Ve" +
      "ctorRequest\032\017.VectorResponse\"\000\0220\n\rsearch" +
      "ByBytes\022\r.BytesRequest\032\016.BytesResponse\"\000" +
      "B \n\016cn.ac.iie.grpcB\014VectorServerP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BytesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BytesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BytesRequest_descriptor,
        new java.lang.String[] { "ImageBytes", });
    internal_static_BytesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BytesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BytesResponse_descriptor,
        new java.lang.String[] { "VectorBytes", "Code", });
    internal_static_BytesResponse_VectorBytesEntry_descriptor =
      internal_static_BytesResponse_descriptor.getNestedTypes().get(0);
    internal_static_BytesResponse_VectorBytesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BytesResponse_VectorBytesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_VectorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VectorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorRequest_descriptor,
        new java.lang.String[] { "BatchQuery", });
    internal_static_VectorRequest_BatchQueryEntry_descriptor =
      internal_static_VectorRequest_descriptor.getNestedTypes().get(0);
    internal_static_VectorRequest_BatchQueryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorRequest_BatchQueryEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MediaTask_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MediaTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MediaTask_descriptor,
        new java.lang.String[] { "ImageUrl", "Code", "Failed", "ImageVectors", });
    internal_static_MediaTask_ImageVectorsEntry_descriptor =
      internal_static_MediaTask_descriptor.getNestedTypes().get(0);
    internal_static_MediaTask_ImageVectorsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MediaTask_ImageVectorsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_VectorResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_VectorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorResponse_descriptor,
        new java.lang.String[] { "BatchVector", });
    internal_static_VectorResponse_BatchVectorEntry_descriptor =
      internal_static_VectorResponse_descriptor.getNestedTypes().get(0);
    internal_static_VectorResponse_BatchVectorEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorResponse_BatchVectorEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
